### ISSUE TITLE
Commands: Include header and data into AddCommand

### ISSUE THREAD

**Issue by ong6** [AY2021S2-CS2103T-T12-4/tp#139]
Include header as a String. 
```-H, --header <header>```

Include data as a String. 
```-d, --data <data>```

So a sample add command format will be.
``` add -x Method -u URL -d data -H Headers -H Headers -t Tags -t Tags```
``` add -x GET -u HTTP://localhost:3000 -d "param1=value1&param2=value2" -H "Content-Type: application/x-www-form-urlencoded" -t values```

Header and Data is optional

**Comment by tjtanjin** [comment]
Resolved in #145
