### ISSUE TITLE
As an expert user, I call up APIs that I have just used recently 

### ISSUE THREAD

**Issue by JulietTeoh** [AY2021S2-CS2103T-T12-4/tp#14]
so that I can enjoy more convenience.

**Comment by tlylt** [comment]
Anyone is currently working on this? If not I chop first...

**Comment by tjtanjin** [comment]
Is this going to be added in the form of a new feature?

**Comment by tlylt** [comment]
> Is this going to be added in the form of a new feature?

yes, I am thinking of upArrow to retrieve the last command.

**Comment by tjtanjin** [comment]
If this gets added before the night can update the UG as well? :D

**Comment by tlylt** [comment]
> If this gets added before the night can update the UG as well? :D

yea sure
