### ISSUE TITLE
Docs: include a link to workflow guide in the product website

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#175]
- maybe add a hyperlink on the page https://ay2021s2-cs2103t-t12-4.github.io/tp/ to link to our workflow guide
- require the workflow guide to also be in the proper format in order to be parsed properly
- this is because we already spend the time writing it, why not display it as well 👀 
- non-urgent, open to discussion

**Comment by tjtanjin** [comment]
I think this is a great suggestion, since v1.2 is being wrapped up let's do it in v1.2b :D
