### ISSUE TITLE
Bug: infrequent stackoverflow error with sample endpoint 3

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#193]
Sample endpoint 3 periodically returns an empty result with the following error:
`"JavaFX Application Thread" java.lang.StackOverflowError`

There is no known way for the user to directly cause it as of the time of writing this. It seems completely random. What is worth pointing out is that sample endpoint 3 returns a `very long json result` which is also reflected in the extra 1 second it takes to load the result into display.

This seems to be a performance issue and we should consider how to address this as soon as possible.

**Comment by tlylt** [comment]
> Sample endpoint 3 periodically returns an empty result with the following error:
> `"JavaFX Application Thread" java.lang.StackOverflowError`
> 
> There is no known way for the user to directly cause it as of the time of writing this. It seems completely random. What is worth pointing out is that sample endpoint 3 returns a `very long json result` which is also reflected in the extra 1 second it takes to load the result into display.
> 
> This seems to be a performance issue and we should consider how to address this as soon as possible.

Have tried a few times and wasn't able trigger it, if it is a peculiarity with regards to this API, perhaps we should remove it as of now.

**Comment by tjtanjin** [comment]
Might have a potential fix to this. Will look at using `appendText` in `ResultDisplay` and update again.

**Comment by tjtanjin** [comment]
Another update, I tried both `appendText` as well as `ListView` instead of `TextArea` in our `ResultDisplay`. In all cases, the lag still features prominently and because the bug is not deterministic, I am also unable to tell if either of them actually fixes anything. With all that said, I have come across quite a number of threads discussing about the performance of JavaFX and in particular, it seems `TextArea` is not good for very lengthy strings. In fact digging deeper there's quite a lot of criticisms for JavaFX performance. With all that said, I will likely opt to catch the stackoverflow exception.

Note: I cannot tag prof damith here but I'll find time to clarify if this can actually be considered a bug of ours. If truly it is because JavaFX is unable to support such lengthy input without crashing, then hopefully it might be considered an inherited bug.

**Comment by tlylt** [comment]
If the length of response is a concern, perhaps we can check the response length and limit that to a reasonable number such that we display a proper error message when the length exceeds that.

**Comment by tjtanjin** [comment]
> If the length of response is a concern, perhaps we can check the response length and limit that to a reasonable number such that we display a proper error message when the length exceeds that.

My concern is that this might be considered a bug as if we consider the fact that our application causes "loss of data" when calling an endpoint. Will really need to clarify soon.

**Comment by tjtanjin** [comment]
The endpoint associated with this error returns a response body of length above 800000 and infrequently crashes in JavaFX when `setText` is called. There seems to be no better way to improve performance for this in JavaFX (have tried `ListView`, staggering the setting of text etc). As this lies with performance issues in JavaFX, it is more practical to address this in our requirements where we "cap" the length of response body for a reasonable performance of the application to be less than 100000.
