### ISSUE TITLE
Bug in Interface: When using edit command, it shows blank fields.

### ISSUE THREAD

**Issue by ong6** [AY2021S2-CS2103T-T12-4/tp#201]
Example:
`edit 1 -x get` will return the following: 
Edited endpoint: GET; Address: dog; Data: {some data}; Headers: key: value; Tags: [data][local]; Last Response: Time Taken:  seconds; ; Status Code: ; Reason Phrase: : Response Body: 

It should only show populated fields.

**Comment by tjtanjin** [comment]
Currently if a field is blank it states `No Data`, does that resolve this issue? @ong6

**Comment by tlylt** [comment]
Seems like it's fixed, @ong6 can verify again.
![image](https://user-images.githubusercontent.com/41845017/111113209-66bd3380-859c-11eb-8447-27f438ac4c0f.png)
