### ISSUE TITLE
Chore: discuss what to do with the blank space on the rightmost panel

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#205]
There is an extra blank space on the right of the app when maximised. Should discuss what to do with it (e.g. remove it, add more animations/meta information into it etc).

**Comment by tlylt** [comment]
I would prefer to remove it i.e. maximize the space by expanding the result display. This is to keep the UI simple and more consistent by ignoring screen size differences, which might be error-prone because we need to cater to various sizes. Just my 2 cents.

**Comment by ong6** [comment]
I agree with yong liang
