### ISSUE TITLE
Feat: include status code reason phrase in meta data on result display

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#209]
The current results look like this:
<img width="302" alt="Screenshot 2021-03-11 at 3 07 42 PM" src="https://user-images.githubusercontent.com/43908963/110749155-af62ad00-827b-11eb-8bcd-102cb1e02f97.png">

Without the reason phrase, it might not be intuitive for what a status code represents. I am inclined to think this should be added, any thoughts?

**Comment by tlylt** [comment]
Given that we can also retrieve the status phrase from `response.getStatusLine().getReasonPhrase()`, perhaps we can have a hover over effect that when users hover over the status, they can see the textual response phrase.

**Comment by tjtanjin** [comment]
Would this compromise the command line friendliness since it involves using the mouse to hover?

**Comment by tlylt** [comment]
Perhaps we could try it out and determine if it makes sense visually. My hope is that it should not be displayed in such a way that clutter the essential information that we are trying to show.

**Comment by tjtanjin** [comment]
Yup this is not high priority so we can try this out and discuss some time later.
