### ISSUE TITLE
Feat: add more distinction for response body in result

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#219]
On a somewhat related note to issue #209 , the endpoint lines (included by us) and response body (obtained from server response) does not have a clear distinction. Having some distinction here might make it easier to see at first glance where the response body starts. Any thoughts?

**Comment by tlylt** [comment]
I think this might be a UI tweak/task where we explore better ways to the layout of the response(both what we extracted out and the actual response entity-body of the API request). Maybe anyone who has thoughts of how our UI could be improved can have a go at this?

**Comment by tjtanjin** [comment]
@AY2021S2-CS2103T-T12-4/developers Just a note that this also remains an important issue with regards to the aspect of **UI refinements** for v1.3.

**Comment by tjtanjin** [comment]
Refer to latest issue at #310
