### ISSUE TITLE
Refactor: remove List command?

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#226]
Given that our UI shows the list permanently on the left-hand side, seems to be unnecessary to keep this command. Any thoughts?

**Comment by tjtanjin** [comment]
Is this the same as the `clear` command?

**Comment by tlylt** [comment]
Ok I think I need to see how find command works first

**Comment by ong6** [comment]
Don't remove the List command, it shows a complete list of all the API's after the find command. There is no way to do that after the find command is run

**Comment by tjtanjin** [comment]
@tlylt @ong6 Is this discussion still ongoing or can it be closed?
