### ISSUE TITLE
Refactor: Run command to have a default shortcut syntax for running get request

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#247]
I think the most common API requests are the get requests to an endpoint, therefore it might be good if we provide a shortcut for that for easy of quick testing.
My idea is that users can simply do `run https://xxxx` to run a default get request, without specifying `-x get -u`
@tjtanjin thoughts?

**Comment by tjtanjin** [comment]
This behavior is also seen in `CURL` so I think it will be a good enhancement :)
