### ISSUE TITLE
Docs: update user guide styling, presentation and appendix

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#285]
One of the main focuses of v1.3. **We should resolve this issue only when all of these have been addressed**. Let's create small issues while updating only parts of the user guide.

While the user guide contains most of the relevant information now, it is still quite a distance from being complete. The following are key points to make changes for:
**Styling**
- The team consensus is that the current styling can be improved. We can explore applying more html elements to improve the readability of the user guide instead of solely relying on markdown.

**Presentation**
- Somewhat related to styling but less technical. We can consider how to better show the information to our users (e.g. using screenshots for every command).

**Appendix**
- This one is huge. Given the nature of our application and the emphasis on having a clear user guide, we will need a rather lengthy appendix to cover information about APIs.

**Comment by tlylt** [comment]
Possibly discuss the progress on this task in the afternoon meeting. From my perspective, I think the UG styling & structure are of decent quality, largely thanks to @tjtanjin. If all features are finalized, perhaps everyone could go through the UG at least once again just to make sure no stones are left unturned.

**Comment by tjtanjin** [comment]
> Possibly discuss the progress on this task in the afternoon meeting. From my perspective, I think the UG styling & structure are of decent quality, largely thanks to @tjtanjin. If all features are finalized, perhaps everyone could go through the UG at least once again just to make sure no stones are left unturned.

There were some new points brought up after the UG today. They are mostly small details and should not be a lot of work. I agree that everyone should go through the UG at least once again, before the mock PE.

**Comment by tjtanjin** [comment]
@AY2021S2-CS2103T-T12-4/developers UG is tentatively complete. Let's quickly go through it one last time during tomorrow's meeting and close this issue. If anyone has time prior to the meeting, help double check the links/examples in the UG.

**Comment by tjtanjin** [comment]
User guide is complete :DDD
