### ISSUE TITLE
Test: add new test cases to cover more grounds

### ISSUE THREAD

**Issue by tjtanjin** [AY2021S2-CS2103T-T12-4/tp#287]
One of the main focuses of v1.3. **We should resolve this issue only when all of these have been addressed**. Let's create small issues while adding test cases for now.

The default test cases are not comprehensive enough for our needs. In our particular, they don't include edge cases that are catered to our morphed product. Instead of doing one-off tests manually while trying the application, let's write them as test cases so that we can be more assured that our future changes are not causing bugs we thought we previously tested for.

**Comment by tlylt** [comment]
There are a few areas where we need to address, at least base on the coverage analysis report by IntelliJ. While some areas such as UI could be disregarded, we should try to cover those cases in Logic, Model, and Commons, possibly discuss further on specific work allocation in the afternoon meeting
![image](https://user-images.githubusercontent.com/41845017/112779202-bf9aca80-9078-11eb-8b8c-032bb8bed055.png)

**Comment by tjtanjin** [comment]
Work on adding test cases have ended. Focus is now on wrapping up documentation and fixing bugs.
