### ISSUE TITLE
UI: remove menu bar?

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#322]
I'm working on the demo slides and thought that since we are going for a simplistic no bs UI, should we remove the menu bar? Right now all it does is to provide an exit button and a help button. For exit, users can simply click the top right corner to close, for help users can simply type in help. Wonder what the rest think?
![image](https://user-images.githubusercontent.com/41845017/111899577-73dc9580-8a68-11eb-985a-24a10a99bc4b.png)

**Comment by NightRaven49** [comment]
I agree with your observation, though instead of removing the menu bar outright, I feel that we can replace it with a banner saying History and Response, much like your original UI mockup.

**Comment by tlylt** [comment]
> I agree with your observation, though instead of removing the menu bar outright, I feel that we can replace it with a banner saying History and Response, much like your original UI mockup. We can discuss this tomorrow along with other UI tweaks we can make this coming week.

Great suggestion, let see what others think tmr

**Comment by tlylt** [comment]
Closed by #393
