### ISSUE TITLE
User guide: Main components & other minor fixes

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#401]
Perhaps we can do away with the first component? Because the header could be treated as part of 2nd and 4th component. Also because we are talking about the Main components here, if we include all the components, then the last component should also be included
![image](https://user-images.githubusercontent.com/41845017/112742975-daf8cd80-8fc5-11eb-989f-89340bd77288.png)
![image](https://user-images.githubusercontent.com/41845017/112742940-9a00b900-8fc5-11eb-8af6-cda3365bd6fb.png)
@tjtanjin thoughts?

**Comment by tjtanjin** [comment]
Yup I agree that makes sense can update it :D
