### ISSUE TITLE
Beautify response for Show, Add and Edit

### ISSUE THREAD

**Issue by ong6** [AY2021S2-CS2103T-T12-4/tp#559]
Add the responseMeta (in ResultDisplay) to the three commands above and update it for send and run.

It should display Method, status, time, protocol version, reason phrase in this order.

**Comment by NightRaven49** [comment]
ok currently i got the tags to show up for these commands, but i realised that the only relevant tag for these commands is the method tag; the other tags do not make sense to be included since no api is actually called.

**Comment by tjtanjin** [comment]
Correct me if I am wrong but the response field should still be there except that it may or may not contain values (depending on whether that endpoint has been ran before).

**Comment by ong6** [comment]
@tjtanjin  yes, there is still a response field

**Comment by JulietTeoh** [comment]
> ok currently i got the tags to show up for these commands, but i realised that the only relevant tag for these commands is the method tag; the other tags do not make sense to be included since no api is actually called, so there is no data to be shown in those tags unless we want to actually run it like the show command.

We want it to show "No Data" in the little box at the top, just like send and run

**Comment by NightRaven49** [comment]
Closed with #572.
