### ISSUE TITLE
Checking error messages

### ISSUE THREAD

**Issue by JulietTeoh** [AY2021S2-CS2103T-T12-4/tp#560]
@tlylt I realised that the index situation has been fixed for edit

just checking if this is the desired error msgs for show and remove. 
index tested: -10, 0, 10, 10000000000000
<img width="1191" alt="Screenshot 2021-04-06 at 11 16 19 PM" src="https://user-images.githubusercontent.com/34907949/113735473-de5f2800-972e-11eb-98a4-6477fc3a3411.png">
<img width="1191" alt="Screenshot 2021-04-06 at 11 16 28 PM" src="https://user-images.githubusercontent.com/34907949/113735487-e0c18200-972e-11eb-84f3-b59a9bad5a02.png">
<img width="1193" alt="Screenshot 2021-04-06 at 11 16 38 PM" src="https://user-images.githubusercontent.com/34907949/113735497-e28b4580-972e-11eb-8529-1f528d544e42.png">

**Comment by tlylt** [comment]
YES!

**Comment by tjtanjin** [comment]
@tlylt Is the allowed range mentioned anywhere in case this gets raised as a bug

**Comment by tlylt** [comment]
> @tlylt Is the allowed range mentioned anywhere in case this gets raised as a bug

will add in a section to explain index in UG

**Comment by JulietTeoh** [comment]
thank u for clarifying
