### ISSUE TITLE
Enhancement to error messages

### ISSUE THREAD

**Issue by JulietTeoh** [AY2021S2-CS2103T-T12-4/tp#567]
If not index if provided for commands EDIT, SHOW, REMOVE, SEND, should we make an error message that says "no index provided" if there is no index provided

E.G, user just types in `show`

currently, all of it says: "Error: Index provided is not a non-zero unsigned integer within the allowed range.", which can be misinterpreted

**Comment by JulietTeoh** [comment]
![Uploading Screenshot 2021-04-07 at 1.38.15 AM.png…]()

**Comment by JulietTeoh** [comment]
I made a hot fix is this ok?

**Comment by tlylt** [comment]
> I made a hot fix is this ok?

I think this is a great point, does it also apply for all other commands when user just do 'add ' or 'run '? If so we can probably give a parameter cannot be empty error as well
