### ISSUE TITLE
DG task: Include an appendix named Instructions for Manual Testing

### ISSUE THREAD

**Issue by tlylt** [AY2021S2-CS2103T-T12-4/tp#581]
![image](https://user-images.githubusercontent.com/41845017/113957495-ea8fd600-9851-11eb-81ad-7d3e8ad1e682.png)

**Comment by tjtanjin** [comment]
In case it was missed out, the appendix for this and `Effort` are already included in the DG but still needs quite a lot of touchup.

**Comment by tlylt** [comment]
> In case it was missed out, the appendix for this and `Effort` are already included in the DG but still needs quite a lot of touchup.

Yes in view of the seriousness of this section, extra attention may be required.

**Comment by NightRaven49** [comment]
I've been working on this since formatting the DG.
